//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CulinaryOasis.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CookingStage
    {
        public int ID { get; set; }
        public Nullable<int> DishID { get; set; }
        public string ProcessDescription { get; set; }
        public Nullable<int> TimeInMinutes { get; set; }
    
        public virtual Dish Dish { get; set; }
    }
}
